<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SecretManager.SecretsDashboard.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecretManager.SecretsDashboard.Domain\SecretManager.SecretsDashboard.Domain.csproj" />
  </ItemGroup>
</Project>
